@startuml
start

:User enters "find t/keyword";
if () then ([keyword is blank])
    :Message: "t/ cannot be blank";
    stop
else ([find t/keyword])
    :Get filtered person list;

    :Update FilteredPersonList with tags;

    :Message: FilteredPersonList.size() + " persons listed!";

    :Display filtered persons to User;
    stop
@enduml
