@startuml
start

:User enters "find t/tags";

if () then ([FindCommand is null])
    :Message: "Tags should be within 25 characters, and it should not be blank";
    stop
else ([FindCommand is not null])
    :FindCommand is executed;

    if () then (isValidTagName is False)
        :Message": "Tags should be within 25 characters, and it should not be blank";
        stop
    else (isValidTagName is True)
        :Get filtered person list;

        :Update FilteredPersonList with tags;

        :Message: FilteredPersonList.size() + " persons listed!";

        :Display filtered persons to User;
        stop
@enduml
